name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Give Actions permission to push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: alokjha01264
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate snake animation"
          add: "dist/snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
